#ifndef PESEC_CONTROL_FLOW_H
#define PESEC_CONTROL_FLOW_H

typedef enum
{
    CONTROL_FLOW_NONE,
    CONTROL_FLOW_BREAK,
    CONTROL_FLOW_CONTINUE,
    CONTROL_FLOW_PANIC,
    CONTROL_FLOW_RETURN,
} control_flow_t;

#endif // PESEC_CONTROL_FLOW_H