/*
 * !!!!!!!!!!!!!!!!!!!!
 * GENERATED BY Z.AI
 * TODO: rewrite this myself
 * !!!!!!!!!!!!!!!!!!!!
 */

#include "../include/number_value.h"
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <limits.h>

#include "include/utils/interpret_info.h"
#include "include/utils/throw.h"

#define NV_BASE 1000000000ULL


static number_value_value_t *nvv_new(void)
{
    number_value_value_t *v = (number_value_value_t *)malloc(sizeof(*v));
    if (!v) THROW("Out of memory: number_value_value_t");
    v->capacity = 4;
    v->size     = 0;
    v->length   = 0;
    v->data     = (ull_t *)calloc(v->capacity, sizeof(ull_t));
    if (!v->data) THROW("Out of memory: number_value_value_t data");
    return v;
}

static void nvv_ensure_capacity(number_value_value_t *v, ull_t need)
{
    if (need <= v->capacity) return;
    ull_t cap = v->capacity ? v->capacity : 4;
    while (cap < need) cap *= 2;
    ull_t *tmp = (ull_t *)realloc(v->data, cap * sizeof(ull_t));
    if (!tmp) THROW("Failed to grow number_value_value_t");
    memset(tmp + v->capacity, 0, (cap - v->capacity) * sizeof(ull_t));
    v->data     = tmp;
    v->capacity = cap;
}

static void nvv_push(number_value_value_t *v, ull_t digit)
{
    nvv_ensure_capacity(v, v->length + 1);
    v->data[v->length++] = digit;
    v->size = v->length;
}

static void nvv_trim_lead(number_value_value_t *v)
{
    if (!v || v->length == 0) return;
    ull_t i = 0;
    while (i < v->length - 1 && v->data[i] == 0) ++i;
    if (i > 0) {
        memmove(v->data, v->data + i, (v->length - i) * sizeof(ull_t));
        v->length -= i;
        v->size    = v->length;
    }
}

static number_value_value_t *nvv_from_string(string_view_t sv)
{
    number_value_value_t *v = nvv_new();
    if (sv.length == 0) {
        nvv_push(v, 0);
        return v;
    }

    /* Парсим с конца строки, собирая по 9 цифр в блок */
    ull_t end = sv.length;
    while (end > 0) {
        ull_t start = end > 9 ? end - 9 : 0;
        ull_t val = 0;
        for (ull_t i = start; i < end; ++i) {
            char c = sv.data[i];
            if (c >= '0' && c <= '9') {
                val = val * 10 + (ull_t)(c - '0');
            }
        }
        nvv_push(v, val);
        end = start;
    }

    /* Переворачиваем массив, чтобы старший блок был первым */
    for (ull_t i = 0; i < v->length / 2; ++i) {
        ull_t tmp = v->data[i];
        v->data[i] = v->data[v->length - 1 - i];
        v->data[v->length - 1 - i] = tmp;
    }

    nvv_trim_lead(v); /* Удаляем возможные ведущие нули */
    if (v->length == 0) nvv_push(v, 0);
    return v;
}

/* Для дробной части мы обязаны дополнять последний блок нулями до 9 цифр! */
static number_value_value_t *nvv_from_string_frac(string_view_t sv)
{
    number_value_value_t *v = nvv_new();
    if (sv.length == 0) return v;

    ull_t pad = (9 - (sv.length % 9)) % 9; /* Сколько нулей добавить в конец */

    ull_t end = sv.length;
    while (end > 0) {
        ull_t start = end > 9 ? end - 9 : 0;
        ull_t val = 0;
        for (ull_t i = start; i < end; ++i) {
            char c = sv.data[i];
            if (c >= '0' && c <= '9') {
                val = val * 10 + (ull_t)(c - '0');
            }
        }
        if (start == 0 && pad > 0) {
            for (ull_t p = 0; p < pad; ++p) val *= 10;
        }
        nvv_push(v, val);
        end = start;
    }

    for (ull_t i = 0; i < v->length / 2; ++i) {
        ull_t tmp = v->data[i];
        v->data[i] = v->data[v->length - 1 - i];
        v->data[v->length - 1 - i] = tmp;
    }
    return v;
}

static number_value_value_t *nvv_clone(const number_value_value_t *src)
{
    if (!src) return NULL;
    number_value_value_t *v = (number_value_value_t *)malloc(sizeof(*v));
    if (!v) THROW("Out of memory: nvv_clone");
    v->capacity = src->capacity ? src->capacity : 1;
    v->size     = src->size;
    v->length   = src->length;
    v->data     = (ull_t *)malloc(v->capacity * sizeof(ull_t));
    if (!v->data) THROW("Out of memory: nvv_clone data");
    memcpy(v->data, src->data, src->length * sizeof(ull_t));
    return v;
}

static void nvv_free(number_value_value_t *v)
{
    if (!v) return;
    free(v->data);
    free(v);
}

static void nvv_trim_trail(number_value_value_t *v)
{
    if (!v || v->length == 0) return;
    while (v->length > 0 && v->data[v->length - 1] == 0) --v->length;
    v->size = v->length;
}

/* Сравнение массивов */
static int nvv_cmp(const number_value_value_t *a, const number_value_value_t *b)
{
    ull_t ia = 0, ib = 0;
    while (ia < a->length - 1 && a->data[ia] == 0) ++ia;
    while (ib < b->length - 1 && b->data[ib] == 0) ++ib;
    ull_t ra = a->length - ia;
    ull_t rb = b->length - ib;
    if (ra != rb) return ra > rb ? 1 : -1;
    for (ull_t k = 0; k < ra; ++k) {
        if (a->data[ia + k] != b->data[ib + k])
            return a->data[ia + k] > b->data[ib + k] ? 1 : -1;
    }
    return 0;
}

/* =========================================================================
 *  number_value_t: открытый API
 * ========================================================================= */

static bool nv_is_zero(const number_value_t *n)
{
    return n->decimal->length == 1
        && n->decimal->data[0] == 0
        && n->fraction->length == 0;
}

number_value_t *number_value_new(const string_view_t decimal, const string_view_t fraction)
{
    number_value_t *n = (number_value_t *)malloc(sizeof(*n));
    if (!n) THROW("Out of memory: number_value_new");
    n->negative = false;
    n->decimal  = nvv_from_string(decimal);
    if (n->decimal->length == 0) nvv_push(n->decimal, 0);
    n->fraction = nvv_from_string_frac(fraction);
    return n;
}

void number_value_free(number_value_t *n)
{
    if (!n) return;
    nvv_free(n->decimal);
    nvv_free(n->fraction);
    free(n);
}

number_value_t *number_value_negate(const number_value_t *n)
{
    if (!n) return NULL;
    number_value_t *r = (number_value_t *)malloc(sizeof(*r));
    if (!r) THROW("Out of memory: number_value_negate");
    r->negative = !n->negative;
    r->decimal  = nvv_clone(n->decimal);
    r->fraction = nvv_clone(n->fraction);
    return r;
}

static number_value_t *nv_clone_full(const number_value_t *src)
{
    if (!src) return NULL;
    number_value_t *r = (number_value_t *)malloc(sizeof(*r));
    if (!r) THROW("Out of memory: nv_clone_full");
    r->negative = src->negative;
    r->decimal  = nvv_clone(src->decimal);
    r->fraction = nvv_clone(src->fraction);
    return r;
}

void number_value_normalize(number_value_t *n)
{
    if (!n) return;
    nvv_trim_lead(n->decimal);
    if (n->decimal->length == 0) nvv_push(n->decimal, 0);
    nvv_trim_trail(n->fraction);
    if (nv_is_zero(n)) n->negative = false;
}

long double number_value_to_long_double(number_value_t *n)
{
    if (!n) return 0.0L;
    long double result = 0.0L;
    for (ull_t i = 0; i < n->decimal->length; ++i)
        result = result * (long double)NV_BASE + (long double)n->decimal->data[i];

    long double frac = 0.0L, div = 1.0L;
    for (ull_t i = 0; i < n->fraction->length; ++i) {
        frac = frac * (long double)NV_BASE + (long double)n->fraction->data[i];
        div *= (long double)NV_BASE;
    }
    if (n->fraction->length > 0) frac /= div;
    result += frac;
    if (n->negative) result = -result;
    return result;
}

number_value_t *number_value_from_long_double(const long double value)
{
    if (isnan(value) || isinf(value))
        THROW("Cannot convert NaN or Inf to number_value");

    const bool negative = value < 0.0L;
    const long double abs_val = negative ? -value : value;

    const unsigned int prec = (unsigned int)interpret_info_get()->number_accurate;
    const size_t bufsz = (size_t)prec + 64;
    char *buffer = (char *)malloc(bufsz);
    if (!buffer) THROW("Out of memory: number_value_from_long_double");

    snprintf(buffer, bufsz, "%.*Lf", prec, abs_val);

    string_view_t dsv = { buffer, 0 };
    string_view_t fsv = { "",    0 };
    char *dot = strchr(buffer, '.');
    if (dot) {
        dsv.data   = buffer;
        dsv.length = (ull_t)(dot - buffer);
        fsv.data   = dot + 1;
        fsv.length = (ull_t)strlen(dot + 1);
    } else {
        dsv.data   = buffer;
        dsv.length = (ull_t)strlen(buffer);
    }
    if (dsv.length == 0) { dsv.data = "0"; dsv.length = 1; }

    number_value_t *num = number_value_new(dsv, fsv);
    num->negative = negative;
    free(buffer);
    number_value_normalize(num);
    return num;
}

/* ----------------------------- Сравнение ----------------------------- */

int number_value_compare_abs(const number_value_t *a, const number_value_t *b)
{
    int c = nvv_cmp(a->decimal, b->decimal);
    if (c != 0) return c;

    const ull_t maxf = a->fraction->length > b->fraction->length
                         ? a->fraction->length : b->fraction->length;
    for (ull_t i = 0; i < maxf; ++i) {
        const ull_t da = i < a->fraction->length ? a->fraction->data[i] : 0;
        const ull_t db = i < b->fraction->length ? b->fraction->data[i] : 0;
        if (da != db) return da > db ? 1 : -1;
    }
    return 0;
}

int number_value_compare(const number_value_t *a, const number_value_t *b)
{
    if (a->negative != b->negative) return a->negative ? -1 : 1;
    const int c = number_value_compare_abs(a, b);
    return a->negative ? -c : c;
}

/* --------------------- Сложение/вычитание модулей --------------------- */

number_value_t *number_value_add_abs(const number_value_t *a, const number_value_t *b)
{
    number_value_t *r = (number_value_t *)malloc(sizeof(*r));
    if (!r) THROW("Out of memory: add_abs");
    r->negative = false;

    const ull_t maxf = a->fraction->length > b->fraction->length
                         ? a->fraction->length : b->fraction->length;
    ull_t *fr = (ull_t *)calloc(maxf ? maxf : 1, sizeof(ull_t));
    if (!fr) THROW("OOM add_abs (frac)");

    ull_t carry = 0;
    for (ull_t i = maxf; i > 0; --i) {
        const ull_t p  = i - 1;
        const ull_t da = p < a->fraction->length ? a->fraction->data[p] : 0;
        const ull_t db = p < b->fraction->length ? b->fraction->data[p] : 0;
        const ull_t s  = da + db + carry;
        fr[p]   = s % NV_BASE;
        carry   = s / NV_BASE;
    }
    r->fraction = nvv_new();
    for (ull_t i = 0; i < maxf; ++i) nvv_push(r->fraction, fr[i]);
    free(fr);

    const ull_t maxi = a->decimal->length > b->decimal->length
                         ? a->decimal->length : b->decimal->length;
    ull_t *ir = (ull_t *)calloc(maxi + 1, sizeof(ull_t));
    if (!ir) THROW("OOM add_abs (int)");

    for (ull_t i = 0; i < maxi; ++i) {
        const ull_t da = i < a->decimal->length
                           ? a->decimal->data[a->decimal->length - 1 - i] : 0;
        const ull_t db = i < b->decimal->length
                           ? b->decimal->data[b->decimal->length - 1 - i] : 0;
        const ull_t s  = da + db + carry;
        ir[maxi - i] = s % NV_BASE;
        carry        = s / NV_BASE;
    }
    ir[0] = carry;

    r->decimal = nvv_new();
    const ull_t start = ir[0] ? 0 : 1;
    for (ull_t i = start; i <= maxi; ++i) nvv_push(r->decimal, ir[i]);
    free(ir);

    number_value_normalize(r);
    return r;
}

number_value_t *number_value_sub_abs(const number_value_t *a, const number_value_t *b)
{
    number_value_t *r = (number_value_t *)malloc(sizeof(*r));
    if (!r) THROW("Out of memory: sub_abs");
    r->negative = false;

    const ull_t maxf = a->fraction->length > b->fraction->length
                         ? a->fraction->length : b->fraction->length;
    ull_t *fr = (ull_t *)calloc(maxf ? maxf : 1, sizeof(ull_t));
    if (!fr) THROW("OOM sub_abs (frac)");

    ull_t borrow = 0;
    for (ull_t i = maxf; i > 0; --i) {
        const ull_t p  = i - 1;
        ull_t da = p < a->fraction->length ? a->fraction->data[p] : 0;
        ull_t db = p < b->fraction->length ? b->fraction->data[p] : 0;
        db += borrow;
        if (da < db) { da += NV_BASE; borrow = 1; } else borrow = 0;
        fr[p] = da - db;
    }
    r->fraction = nvv_new();
    for (ull_t i = 0; i < maxf; ++i) nvv_push(r->fraction, fr[i]);
    free(fr);

    const ull_t maxi = a->decimal->length;
    ull_t *ir = (ull_t *)calloc(maxi ? maxi : 1, sizeof(ull_t));
    if (!ir) THROW("OOM sub_abs (int)");

    borrow = 0;
    for (ull_t i = 0; i < maxi; ++i) {
        ull_t da = a->decimal->data[a->decimal->length - 1 - i];
        ull_t db = i < b->decimal->length
                     ? b->decimal->data[b->decimal->length - 1 - i] : 0;
        db += borrow;
        if (da < db) { da += NV_BASE; borrow = 1; } else borrow = 0;
        ir[maxi - 1 - i] = da - db;
    }

    r->decimal = nvv_new();
    ull_t start = 0;
    while (start < maxi - 1 && ir[start] == 0) ++start;
    for (ull_t i = start; i < maxi; ++i) nvv_push(r->decimal, ir[i]);
    free(ir);

    number_value_normalize(r);
    return r;
}

number_value_t *number_value_add(const number_value_t *a, const number_value_t *b)
{
    if (!a || !b) return NULL;
    number_value_t *r;
    if (a->negative == b->negative) {
        r = number_value_add_abs(a, b);
        r->negative = a->negative;
    } else {
        const int c = number_value_compare_abs(a, b);
        if (c > 0)      { r = number_value_sub_abs(a, b); r->negative = a->negative; }
        else if (c < 0) { r = number_value_sub_abs(b, a); r->negative = b->negative; }
        else            { r = number_value_new(string_view_from("0"), string_view_from("")); }
    }
    number_value_normalize(r);
    return r;
}

number_value_t *number_value_sub(const number_value_t *a, const number_value_t *b)
{
    if (!a || !b) return NULL;
    number_value_t *nb = number_value_negate(b);
    number_value_t *r  = number_value_add(a, nb);
    number_value_free(nb);
    return r;
}

/* ----------------------------- Умножение ----------------------------- */

ull_t *multiply_integer(const ull_t *a, ull_t alen,
                        const ull_t *b, ull_t blen,
                        ull_t *out_length)
{
    if (alen == 0 || blen == 0) {
        *out_length = 1;
        ull_t *z = (ull_t *)malloc(sizeof(ull_t));
        if (!z) THROW("OOM multiply_integer zero");
        z[0] = 0;
        return z;
    }
    ull_t rl = alen + blen;
    ull_t *r = (ull_t *)calloc(rl, sizeof(ull_t));
    if (!r) THROW("OOM multiply_integer");

    for (ull_t i = alen; i > 0; --i) {
        ull_t carry = 0;
        for (ull_t j = blen; j > 0; --j) {
            const ull_t pos = (i - 1) + (j - 1) + 1;
            const ull_t m   = a[i - 1] * b[j - 1] + r[pos] + carry;
            r[pos] = m % NV_BASE;
            carry  = m / NV_BASE;
        }
        r[i - 1] += carry;
    }

    ull_t start = 0;
    while (start < rl - 1 && r[start] == 0) ++start;
    if (start > 0) {
        memmove(r, r + start, (rl - start) * sizeof(ull_t));
        rl -= start;
    }
    *out_length = rl;
    return r;
}

number_value_t *number_value_mul(const number_value_t *a, const number_value_t *b)
{
    if (!a || !b) return NULL;

    const ull_t fa = a->fraction->length;
    const ull_t fb = b->fraction->length;
    const ull_t total_frac = fa + fb;

    const ull_t la = a->decimal->length + fa;
    ull_t *da = (ull_t *)calloc(la ? la : 1, sizeof(ull_t));
    if (!da) THROW("OOM mul da");
    ull_t p = 0;
    for (ull_t i = 0; i < a->decimal->length; ++i) da[p++] = a->decimal->data[i];
    for (ull_t i = 0; i < fa; ++i)               da[p++] = a->fraction->data[i];

    const ull_t lb = b->decimal->length + fb;
    ull_t *db = (ull_t *)calloc(lb ? lb : 1, sizeof(ull_t));
    if (!db) THROW("OOM mul db");
    p = 0;
    for (ull_t i = 0; i < b->decimal->length; ++i) db[p++] = b->decimal->data[i];
    for (ull_t i = 0; i < fb; ++i)               db[p++] = b->fraction->data[i];

    ull_t plen;
    ull_t *prod = multiply_integer(da, la, db, lb, &plen);
    free(da); free(db);

    if (plen < total_frac) {
        ull_t *np = (ull_t *)calloc(total_frac, sizeof(ull_t));
        if (!np) THROW("OOM mul pad");
        const ull_t off = total_frac - plen;
        memcpy(np + off, prod, plen * sizeof(ull_t));
        free(prod);
        prod = np;
        plen = total_frac;
    }
    const ull_t int_len = plen - total_frac;

    number_value_t *r = (number_value_t *)malloc(sizeof(*r));
    if (!r) THROW("OOM mul result");
    r->negative = a->negative ^ b->negative;
    r->decimal  = nvv_new();
    if (int_len > 0)
        for (ull_t i = 0; i < int_len; ++i) nvv_push(r->decimal, prod[i]);
    else
        nvv_push(r->decimal, 0);
    r->fraction = nvv_new();
    for (ull_t i = int_len; i < plen; ++i) nvv_push(r->fraction, prod[i]);
    free(prod);

    number_value_normalize(r);
    return r;
}

/* ----------------------------- Деление ----------------------------- */

static void nv_shift_right(number_value_t *n, ull_t K)
{
    if (K == 0) return;
    if (n->fraction->length >= K) {
        for (ull_t i = 0; i < K; ++i)
            nvv_push(n->decimal, n->fraction->data[i]);
        memmove(n->fraction->data, n->fraction->data + K,
                (n->fraction->length - K) * sizeof(ull_t));
        n->fraction->length -= K;
        n->fraction->size    = n->fraction->length;
    } else {
        const ull_t mv = n->fraction->length;
        for (ull_t i = 0; i < mv; ++i)
            nvv_push(n->decimal, n->fraction->data[i]);
        const ull_t zeros = K - mv;
        for (ull_t i = 0; i < zeros; ++i) nvv_push(n->decimal, 0);
        n->fraction->length = 0;
        n->fraction->size    = 0;
    }
    nvv_trim_lead(n->decimal);
}

static void nv_rem_shift(number_value_value_t *v, ull_t digit)
{
    if (v->length == 1 && v->data[0] == 0) v->data[0] = digit;
    else nvv_push(v, digit);
}

static void nv_rem_sub(number_value_value_t *rem, const number_value_value_t *div)
{
    const ull_t rl = rem->length;
    const ull_t dl = div->length;
    ull_t borrow = 0;
    for (ull_t i = 0; i < dl; ++i) {
        const ull_t ri = rl - 1 - i;
        const ull_t di = dl - 1 - i;
        ull_t rv = rem->data[ri];
        const ull_t dv = div->data[di] + borrow;
        if (rv < dv) { rv += NV_BASE; borrow = 1; } else borrow = 0;
        rem->data[ri] = rv - dv;
    }
    ull_t i = dl;
    while (borrow && i < rl) {
        const ull_t ri = rl - 1 - i;
        if (rem->data[ri] == 0) { rem->data[ri] = NV_BASE - 1; borrow = 1; }
        else { rem->data[ri]--; borrow = 0; }
        ++i;
    }
    nvv_trim_lead(rem);
}

/* Умножение массива на число (для оценки частного) */
static number_value_value_t *nvv_mul_ull(const number_value_value_t *a, ull_t mul)
{
    number_value_value_t *r = nvv_new();
    if (mul == 0) {
        nvv_push(r, 0);
        return r;
    }
    nvv_ensure_capacity(r, a->length + 1);
    ull_t carry = 0;
    for (ull_t i = a->length; i > 0; --i) {
        ull_t p = i - 1;
        ull_t prod = a->data[p] * mul + carry;
        r->data[p + 1] = prod % NV_BASE;
        carry = prod / NV_BASE;
    }
    r->data[0] = carry;
    r->length = a->length + 1;
    r->size = r->length;
    nvv_trim_lead(r);
    return r;
}

/* Бинарный поиск следующей цифры частного (от 0 до NV_BASE-1) */
static ull_t nv_div_estimate(number_value_value_t *rem, const number_value_value_t *div) {
    ull_t cnt = 0;
    ull_t low = 0, high = NV_BASE - 1;
    while (low <= high) {
        ull_t mid = low + (high - low) / 2;
        number_value_value_t *prod = nvv_mul_ull(div, mid);
        int cmp = nvv_cmp(prod, rem);
        nvv_free(prod);
        if (cmp <= 0) {
            cnt = mid;
            low = mid + 1;
        } else {
            if (mid == 0) break;
            high = mid - 1;
        }
    }
    if (cnt > 0) {
        number_value_value_t *prod = nvv_mul_ull(div, cnt);
        nv_rem_sub(rem, prod);
        nvv_free(prod);
    }
    return cnt;
}

number_value_t *number_value_div(const number_value_t *a, const number_value_t *b)
{
    if (!a || !b) return NULL;
    if (nv_is_zero(b)) THROW("Division by zero is not allowed");
    if (nv_is_zero(a)) return number_value_new(string_view_from("0"), string_view_from(""));

    const bool res_neg = a->negative ^ b->negative;

    number_value_t *A = nv_clone_full(a);
    number_value_t *B = nv_clone_full(b);

    const ull_t K = B->fraction->length;
    nv_shift_right(A, K);
    nv_shift_right(B, K);

    number_value_value_t *rem   = nvv_new(); nvv_push(rem, 0);
    number_value_value_t *q_dec = nvv_new();

    for (ull_t i = 0; i < A->decimal->length; ++i) {
        nv_rem_shift(rem, A->decimal->data[i]);
        ull_t cnt = nv_div_estimate(rem, B->decimal);
        nvv_push(q_dec, cnt);
    }
    nvv_trim_lead(q_dec);

    number_value_value_t *q_frac = nvv_new();

    /* Точность: переводим количество цифр в количество блоков */
    ull_t max_frac = interpret_info_get()->number_accurate;
    ull_t max_frac_blocks = max_frac / 9 + 1;
    ull_t fc = 0;

    for (ull_t i = 0; i < A->fraction->length && fc < max_frac_blocks; ++i) {
        nv_rem_shift(rem, A->fraction->data[i]);
        ull_t cnt = nv_div_estimate(rem, B->decimal);
        nvv_push(q_frac, cnt);
        ++fc;
    }

    while (fc < max_frac_blocks) {
        if (rem->length == 1 && rem->data[0] == 0) break;
        nv_rem_shift(rem, 0);
        ull_t cnt = nv_div_estimate(rem, B->decimal);
        nvv_push(q_frac, cnt);
        ++fc;
    }
    nvv_trim_trail(q_frac);

    number_value_t *r = (number_value_t *)malloc(sizeof(*r));
    if (!r) THROW("OOM div result");
    r->negative = res_neg;
    r->decimal  = q_dec;
    r->fraction = q_frac;

    if (nv_is_zero(r)) r->negative = false;
    number_value_normalize(r);

    number_value_free(A);
    number_value_free(B);
    nvv_free(rem);
    return r;
}

number_value_t *number_value_floor_div(const number_value_t *a, const number_value_t *b)
{
    if (!a || !b) return NULL;
    if (nv_is_zero(b)) THROW("Division by zero is not allowed");

    const bool res_neg = a->negative ^ b->negative;

    number_value_t *A = nv_clone_full(a);
    number_value_t *B = nv_clone_full(b);

    const ull_t K = B->fraction->length;
    nv_shift_right(A, K);
    nv_shift_right(B, K);

    number_value_value_t *rem   = nvv_new(); nvv_push(rem, 0);
    number_value_value_t *q_dec = nvv_new();

    for (ull_t i = 0; i < A->decimal->length; ++i) {
        nv_rem_shift(rem, A->decimal->data[i]);
        ull_t cnt = nv_div_estimate(rem, B->decimal);
        nvv_push(q_dec, cnt);
    }
    nvv_trim_lead(q_dec);

    const bool has_rem =
        (rem->length > 1 || rem->data[0] != 0) || (A->fraction->length > 0);

    if (res_neg && has_rem) {
        number_value_t *temp_q = (number_value_t *)malloc(sizeof(*temp_q));
        if (!temp_q) THROW("OOM floor_div temp");
        temp_q->negative = false;
        temp_q->decimal  = q_dec;
        temp_q->fraction = nvv_new();

        number_value_t *one   = number_value_new(string_view_from("1"), string_view_from(""));
        number_value_t *new_q = number_value_add_abs(temp_q, one);

        nvv_free(temp_q->fraction);
        free(temp_q);
        number_value_free(one);

        q_dec = new_q->decimal;
        new_q->decimal = NULL;
        number_value_free(new_q);
    }

    number_value_t *r = (number_value_t *)malloc(sizeof(*r));
    if (!r) THROW("OOM floor_div result");
    r->negative = res_neg;
    r->decimal  = q_dec;
    r->fraction = nvv_new();
    nvv_push(r->fraction, 0);

    number_value_normalize(r);

    number_value_free(A);
    number_value_free(B);
    nvv_free(rem);
    return r;
}

number_value_t *number_value_pow(const number_value_t *base, const number_value_t *exp)
{
    if (!base || !exp) return NULL;
    if (exp->fraction->length > 0)
        THROW("Exponent must be an integer");

    long long e = 0;
    for (ull_t i = 0; i < exp->decimal->length; ++i) {
        const long long d = (long long)exp->decimal->data[i];
        if (e > (LLONG_MAX - d) / NV_BASE)
            THROW("Exponent is too large");
        e = e * (long long)NV_BASE + d;
    }
    const bool neg_exp = exp->negative;
    if (neg_exp) e = -e;

    if (nv_is_zero(base)) {
        if (e < 0)  THROW("Cannot compute 0 to a negative power");
        if (e == 0) return number_value_new(string_view_from("1"), string_view_from(""));
        return number_value_new(string_view_from("0"), string_view_from(""));
    }

    if (e == 0)
        return number_value_new(string_view_from("1"), string_view_from(""));

    number_value_t *result = number_value_new(string_view_from("1"), string_view_from(""));
    number_value_t *b      = nv_clone_full(base);
    long long k = e < 0 ? -e : e;

    while (k > 0) {
        if (k & 1) {
            number_value_t *t = number_value_mul(result, b);
            number_value_free(result);
            result = t;
        }
        k >>= 1;
        if (k > 0) {
            number_value_t *t = number_value_mul(b, b);
            number_value_free(b);
            b = t;
        }
    }
    number_value_free(b);

    if (neg_exp) {
        number_value_t *one = number_value_new(string_view_from("1"), string_view_from(""));
        number_value_t *r   = number_value_div(one, result);
        number_value_free(one);
        number_value_free(result);
        return r;
    }
    return result;
}